apiVersion: v1
kind: Service
metadata:
  name: pro-service
spec:
  selector:
    app: pro
  ports:
    - protocol: TCP
      port: 80         # External Port
      targetPort: 3003 # Your container's port
  type: LoadBalancer

